# Generated by Django 5.2.6 on 2026-07-27 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_document_model'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='related_contact_id',
        ),
        migrations.AddField(
            model_name='document',
            name='related_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='document',
            name='related_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='contacts.organization'),
        ),
    ]
