# Generated by Django 5.2.6 on 2026-07-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('SALES', 'Sales'), ('PROJECTS', 'Projects')], help_text='Required when role is Manager; must be blank for all other roles.', max_length=20, null=True),
        ),
    ]
