# Generated by Django 5.2.6 on 2026-08-01 18:34

import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='department',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SALES_REP', 'Sales Representative'), ('SALES_MANAGER', 'Sales Manager'), ('PROJECT_MANAGER', 'Project Manager'), ('CEO', 'CEO / Directors'), ('ADMIN', 'Administrator')], default='SALES_REP', help_text='The functional role of the user.', max_length=20),
        ),
    ]
