# Generated by Django 5.2.6 on 2026-08-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers_remove_user_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="The user's contact phone number.", max_length=20, null=True),
        ),
    ]
