# Generated by Django 5.2.6 on 2026-08-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SALES_REP', 'Sales Representative'), ('SALES_MANAGER', 'Sales Manager'), ('TECH_LEAD', 'Tech Lead'), ('FINANCE_OFFICER', 'Finance Officer'), ('ADMIN', 'Administrator')], default='SALES_REP', help_text='The functional role of the user.', max_length=20),
        ),
    ]
